Courses/urls.py
from django.contrib import admin
from django.urls import path, include
from new_users.views import CustomLoginView, CustomLogoutView, RegisterView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MyCourses.urls')),
    path('accounts/login/', CustomLoginView.as_view(), name='login'),
    path('accounts/logout/', CustomLogoutView.as_view(), name='logout'),
    path('accounts/register/', RegisterView.as_view(), name='register'),
    path('accounts/', include('new_users.urls')),
]

Courses5_update/Config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('courses/', include('courses.urls', namespace='courses')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Courses5_update/new_users/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .apps import UsersConfig
from .views import LoginView, LogoutView, RegisterView, get_verification, RegisterInfo, UserListView, \
    UserUpdateView, UserDetailView, UserDeleteView, PasswordResetView, UserPasswordChangeView, PasswordResetDoneView, \
    PasswordResetCompleteView, MyPasswordResetConfirmView, UserCustomUpdateView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('verification_check/', RegisterInfo.as_view(), name='verification_check'),
    path('email_verify/<str:verification_code>/', get_verification, name='verification'),
    path('verification_approve/', TemplateView.as_view(
        template_name='users/verification_approve.html'),
        name='verification_approve'),
    path('verification_reject/', TemplateView.as_view(
        template_name='users/verification_reject.html'),
        name='verification_reject'),
    path('user_list/', UserListView.as_view(), name='user_list'),
    path('user_update/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
    path('user_custom_update/<int:pk>/', UserCustomUpdateView.as_view(), name='user_custom_update'),
    path('user_detail/<int:pk>/', UserDetailView.as_view(), name='user_detail'),
    path('user_delete/<int:pk>/', UserDeleteView.as_view(), name='user_delete'),

    path('password_change/', UserPasswordChangeView.as_view(), name='password_change'),
    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', MyPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

new_users/urls.py
from django.urls import path
from .views import RegisterView, CustomLoginView, CustomLogoutView


urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
]

Courses5_update/new_users/models.py
"""
Модуль: Модель пользователя
Этот модуль содержит модель пользователя для приложения.
"""

from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


NULLABLE = {
    'null': True,
    'blank': True,
}


class User(AbstractUser):
    """
    Пользовательская модель с дополнительными полями и разрешениями.
    """
    username = None
    email = models.EmailField(
        unique=True,
        verbose_name='почта')

    phone = models.CharField(
        max_length=50,
        verbose_name='номер телефона',
        **NULLABLE)
    avatar = models.ImageField(
        upload_to='users/',
        verbose_name='аватар',
        **NULLABLE)
    verification_code = models.CharField(
        max_length=25,
        verbose_name='проверочный код',
        **NULLABLE)

    is_superuser = models.BooleanField(
        default=False,
        verbose_name='администратор сервиса')
    is_staff = models.BooleanField(
        default=False,
        verbose_name='сотрудник сервиса')
    is_active = models.BooleanField(
        default=False,
        verbose_name='метка активности')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'пользователь'
        verbose_name_plural = 'пользователи'
        ordering = ('pk',)

        permissions = [
            ('set_is_activated', 'переключатель метки активности')
        ]

new_users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin

class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('Email is required')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self.create_user(email, password, **extra_fields)

class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    phone = models.TextField(max_length=30)
    city = models.CharField(max_length=100)
    avatar = models.ImageField(upload_to='avatars/', null=True, blank=True)

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['phone', 'city']

    def __str__(self):
        return self.email

Courses5_update/new_users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from .models import User


class StyleFormMiXin(forms.Form):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name != 'is_active':
                field.widget.attrs['class'] = 'form-control'


class LoginViewForm(StyleFormMiXin, AuthenticationForm):

    class Meta:
        model = User
        fields = '__all__'


class UserRegisterForm(StyleFormMiXin, UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2',)


class UserUpdateForm(StyleFormMiXin, UserChangeForm):
    class Meta:
        model = User
        fields = (
            'email',
            'first_name',
            'last_name',
            'phone',
            'avatar',
            'password')
        widgets = {
            'password': forms.HiddenInput(),
        }

    password = forms.CharField(
        label='reset',
        max_length=256,
        widget=forms.HiddenInput())


class UserUpdateCustomForm(StyleFormMiXin, UserChangeForm):
    class Meta:
        model = User
        fields = ('is_active',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()


class UserPasswordForm(StyleFormMiXin, forms.Form):
    old_password = forms.CharField(
        widget=forms.PasswordInput,
        label='Старый пароль')
    new_password1 = forms.CharField(
        widget=forms.PasswordInput,
        label='Новый пароль')
    new_password2 = forms.CharField(
        widget=forms.PasswordInput,
        label='Подтверждение нового пароля')

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super().__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super().clean()
        new_password1 = cleaned_data.get('new_password1')
        new_password2 = cleaned_data.get('new_password2')

        if new_password1 and new_password2 and new_password1 != new_password2:
            raise forms.ValidationError('пароли не совпадают')

        return cleaned_data

    def save(self, commit=True):
        password = self.cleaned_data.get('new_password1')
        self.user.set_password(password)
        if commit:
            self.user.save()
        return self.user

new_users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import CustomUser

class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'password1', 'password2']

class UserLoginForm(AuthenticationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'password']

Courses5_update/new_users/views.py
from django.conf import settings
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.views import LoginView as BaseLoginView, PasswordChangeView, PasswordResetConfirmView
from django.contrib.auth.views import LogoutView as BaseLogoutView
from django.contrib.auth.views import PasswordResetView as BasePasswordResetCompleteView
from django.contrib.auth.views import PasswordResetView as BasePasswordResetDoneView
from django.contrib.auth.views import PasswordResetView as BasePasswordResetView
from django.contrib.sites.shortcuts import get_current_site
from django.core.exceptions import ValidationError
from django.core.mail import send_mail
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, TemplateView, ListView, UpdateView, DetailView, DeleteView

from mailing.views import BaseContextMixin
from .forms import LoginViewForm, UserRegisterForm, UserUpdateForm, UserPasswordForm, UserUpdateCustomForm
from .models import User


class LoginView(BaseContextMixin, BaseLoginView):
    model = User
    form_class = LoginViewForm
    template_name = 'users/login.html'
    extra_context = {
        'title': 'Вход пользователя',
        'phrases': BaseContextMixin.phrases,
    }
    success_url = reverse_lazy('users/home.html')



class LogoutView(BaseLogoutView):
    success_url = reverse_lazy('users/login.html')


class RegisterView(BaseContextMixin, CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    extra_context = {
        'title': 'Регистрация пользователя',
        'phrases': BaseContextMixin.phrases,
    }

    def form_valid(self, form):
        password = User.objects.make_random_password()
        new_user = form.save(commit=False)
        new_user.is_active = False
        new_user.verification_code = password
        new_user.save()

        current_site = get_current_site(self.request)
        url = f'http://{current_site}/users/email_verify/{new_user.verification_code}/'

        send_mail(
            recipient_list=[
                new_user.email],
            subject='Подтвердите ваш почтовый адрес',
            message=f'Для завершения регистрации на сайте перейдите по ссылке: {url}',
            from_email=settings.EMAIL_HOST_USER,
        )

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('users:verification_check') + \
            f'?email={self.object.email}'


class RegisterInfo(TemplateView):
    template_name = 'users/verification_check.html'

    extra_context = {
        'title': 'Подтвердите регистрацию',
    }

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_email = self.request.GET.get('email')
        context['info'] = f'На ваш почтовый адрес {user_email} была отправлена ссылка для завершения регистрации.'
        return context


class UserListView(BaseContextMixin, ListView):
    model = User
    extra_context = {
        'title': 'Список пользователей сервиса',
        'phrases': BaseContextMixin.phrases,
    }


class UserUpdateView(BaseContextMixin, UpdateView):
    model = User
    form_class = UserUpdateForm

    extra_context = {
        'title': 'Редактирование пользователя',
        'phrases': BaseContextMixin.phrases,
    }

    def get_success_url(self):
        return reverse('users:user_detail', args=[self.kwargs.get('pk')])


class UserCustomUpdateView(
        PermissionRequiredMixin,
        BaseContextMixin,
        UpdateView):
    model = User
    form_class = UserUpdateCustomForm
    permission_required = 'users.set_is_activated'

    extra_context = {
        'title': 'Редактирование пользователя',
        'phrases': BaseContextMixin.phrases,
    }

    def get_success_url(self):
        return reverse('users:user_detail', args=[self.kwargs.get('pk')])


class UserDetailView(BaseContextMixin, DetailView):
    model = User
    extra_context = {
        'title': 'Просмотр пользователя',
        'phrases': BaseContextMixin.phrases,
    }


class UserDeleteView(BaseContextMixin, DeleteView):
    model = User
    success_url = reverse_lazy('users:register')
    extra_context = {
        'title': 'Удаление пользователя',
        'phrases': BaseContextMixin.phrases,
    }


class UserPasswordChangeView(BaseContextMixin, PasswordChangeView):
    form_class = UserPasswordForm
    template_name = 'users/password_change.html'

    def get_object(self, queryset=None):
        return self.request.user

    def get_success_url(self):
        return reverse_lazy(
            'users:user_update', kwargs={
                'pk': self.request.user.pk})


class PasswordResetView(BasePasswordResetView):
    template_name = 'users/password_reset_form.html'
    email_template_name = 'users/password_reset_email.html'
    from_email = settings.EMAIL_HOST_USER
    success_url = reverse_lazy('users:password_reset_done')


class PasswordResetDoneView(BasePasswordResetDoneView):
    template_name = 'users/password_reset_done.html'


class MyPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'users/password_reset_confirm.html'
    success_url = reverse_lazy('users:password_reset_complete')


class PasswordResetCompleteView(BasePasswordResetCompleteView):
    template_name = 'users/password_reset_complete.html'
    success_url = reverse_lazy('users:login')


def get_verification(request, verification_code):
    try:
        user = User.objects.filter(verification_code=verification_code).first()
        user.is_active = True
        user.save()
        return redirect('users:verification_approve')
    except (AttributeError, ValidationError):
        return redirect('users:verification_reject')

new_users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.views import View
from django.contrib.auth.views import LoginView, LogoutView
from .forms import UserRegistrationForm, UserLoginForm

class RegisterView(View):
    template_name = 'register.html'

    def get(self, request):
        form = UserRegistrationForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
        return render(request, self.template_name, {'form': form})

class CustomLoginView(LoginView):
    template_name = 'new_users/login.html'
    form_class = UserLoginForm

class CustomLogoutView(LogoutView):
    next_page = 'home'

Courses5_update/new_users/templates/users/login.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="col-12">
    <form class="form-signin" method="post">

        <div class="card mx-auto" style="width: 50%;">
            <div class="card-header">
                <h3 class="card-title">
                    {{ title }}
                </h3>
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-success d-block mx-auto">Войти</button>
                <a href="{% url 'users:password_reset' %}">Забыли пароль?</a>
            </div>
        </div>
    </form>
</div>
{% endblock %}

Courses5_update/new_users/templates/users/password_change.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="col-12">
    <form class="form-signin" method="post">

        <div class="card mx-auto" style="width: 50%;">
            <div class="card-header">
                <h3 class="card-title">
                    {{ title }}
                </h3>
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-success d-block mx-auto">Сменить пароль</button>
            </div>
        </div>
    </form>
</div>
{% endblock %}

Courses5_update/new_users/templates/users/password_reset_complete.html
{% extends 'mailing/base.html' %}

{% block content %}
<div style="display: flex; flex-direction: column; align-items: center; justify-content: center; height: 20;">
    <h3 class="card-title" style="margin-top: 0;">
        Пароль для пользователя успешно сменен.
    </h3>
    <p style="margin-top: 20px;">
        <a class="p-2 btn btn-success" href="{% url 'users:login' %}">Войти</a>
    </p>
</div>
{% endblock %}

Courses5_update/new_users/templates/users/password_reset_confirm.html
{% extends 'mailing/base.html' %}

{% block content %}
<div style="display: flex; justify-content: center;">
  <form method="post">
    {% csrf_token %}
    <h1>Подтверждение сброса пароля</h1>
    <p>Введите новый пароль:</p>
    {{ form.as_p }}
    <button type="submit" class="btn btn-success d-block mx-auto">Сбросить пароль</button>
  </form>
</div>
{% endblock %}

Courses5_update/new_users/templates/users/password_reset_done.html
{% extends 'mailing/base.html' %}

{% block content %}
<div style="display: flex; justify-content: center;">

    <h3 class="card-title">
        Инструкция по восстановлению пароля отправлена на указанный email
    </h3>

</div>
{% endblock %}

Courses5_update/new_users/templates/users/password_reset_email.html
Перейдите по ссылке, чтобы изменить пароль.
{{ protocol }}://{{ domain }}{% url "users:password_reset_confirm" uidb64=uid token=token %}

Courses5_update/new_users/templates/users/password_reset_form.html
{% extends 'mailing/base.html' %}

{% block content %}
<div style="display: flex; justify-content: center;">
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success d-block mx-auto">Отправить</button>
  </form>
</div>
{% endblock %}

Courses5_update/new_users/templates/users/register.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="col-12">
    <form class="form-signin" method="post">

        <div class="card mx-auto" style="width: 50%;">
            <div class="card-header">
                <h3 class="card-title">
                    {{ title }}
                </h3>
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-success d-block mx-auto">Регистрация</button>
            </div>
        </div>
    </form>
</div>
{% endblock %}

Courses5_update/new_users/templates/users/user_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
<section class="jumbotron text-center">
    <div class="container">
        <div class="col-12">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <form method="post">
                                {% csrf_token %}
                                <p>Вы действительно хотите удалить пользователя "{{ object.pk }}" ?</p>
                                <button type="submit" class="btn btn-danger">Подтвердить</button>
                                <a href="{% url 'users:user_detail' object.pk %}" class="btn btn-primary">Отмена</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

Courses5_update/new_users/templates/users/user_detail.html
{% extends 'mailing/base.html' %}

{% load tags %}

{% block content %}

<div class="container">
    <div class="card-deck mb-3 text-center">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Пользователь номер: {{ object.id }}</h4>
            </div>
            <div class="card-body">
                <img src="{% media_tag object.avatar %}" class="img-fluid rounded-start" alt="Image"
                    style="width: 25%;">
                <ul class="list-unstyled mt-3 mb-4">
                    <li>Имя: {{ object.first_name|default:"не указано" }}</li>
                    <li>Фамилия: {{ object.last_name|default:"не указана" }}</li>
                    <li>Почта: {{ object.email|default:"не указана" }}</li>
                    <li>Телефон: {{ object.phone|default:"не указан" }}</li>
                </ul>
                <div class="btn-group">
                    {% if perms.users.set_is_activated %}
                    <a href="{% url 'users:user_custom_update' object.pk %}" type="button"
                        class="btn btn-sm btn-outline-primary">Редактировать</a>
                    <a href="{% url 'users:user_list' %}" type="button" class="btn btn-sm btn-outline-primary">К
                        списку</a>
                    {% else %}
                    <a href="{% url 'users:user_delete' object.pk %}" type="button"
                        class="btn btn-sm btn-outline-primary">Удалить</a>
                    <a href="{% url 'users:user_update' object.pk %}" type="button"
                        class="btn btn-sm btn-outline-primary">Редактировать</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

Courses5_update/new_users/templates/users/user_form.html
{% extends 'mailing/base.html' %}

{% block content %}
<section class="jumbotron text-center">
    <div class="container">
        <div class="col-12">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <form method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                {{ form.as_p }}
                                {% if object %}
                                {% if not perms.users.set_is_activated %}
                                <a href="{% url 'users:password_change' %}" class="btn btn-warning">Сменить пароль</a>
                                {% endif %}
                                {% endif %}
                                <button type="submit" class="btn btn-success">
                                    {% if object %}
                                    Сохранить изменения
                                    {% else %}
                                    Создать
                                    {% endif %}
                                </button>
                                <a href="{% url 'users:user_list' %}" class="btn btn-primary">Отмена</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

Courses5_update/new_users/templates/users/user_list.html
{% extends 'mailing/base.html' %}

{% load tags %}

{% block content %}
<div class="container">
    <div class="row">
        {% for object in object_list %}
        <div class="col-md-4">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    {% if object.is_active %}
                    <small class="text-success">Активирован</small>
                    {% else %}
                    <small class="text-danger">Заблокирован</small>
                    {% endif %}
                </div>
                <div class="card-body">
                    <h4 class="card-title">Пользователь номер: {{ object.id }}</h4>
                    <img src="{% media_tag object.avatar %}" class="img-fluid rounded-start" alt="Image"
                        style="width: 100%;">
                    <ul class="list-unstyled mt-3 mb-4">
                        <li>Имя пользователя: {{ object.first_name|default:"не указано" }}</li>
                        <li>Фамилия пользователя: {{ object.last_name|default:"не указана" }}</li>
                        <li>Почта пользователя: {{ object.email|default:"не указана" }}</li>
                        <li>Телефон пользователя: {{ object.phone|default:"не указан" }}</li>
                    </ul>
                    <div class="btn-group">
                        <a href="{% url 'users:user_detail' object.pk %}"
                            class="btn btn-sm btn-outline-primary">Подробности</a>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

Courses5_update/new_users/templates/users/verification_approve.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="row text-center">
    <div class="col-12">
        <h4>Регистрация завершена успешно.</h4>
        <a class="p-2 btn btn-success" href="{% url 'users:login' %}">Войти</a>
    </div>
</div>
{% endblock %}

Courses5_update/new_users/templates/users/verification_check.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="row text-center">
    <div class="col-12">
        <h4>{{ info }}</h4>
    </div>
</div>
{% endblock %}