Courses/urls.py
from django.contrib import admin
from django.urls import path, include
from new_users.views import CustomLoginView, CustomLogoutView, RegisterView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MyCourses.urls')),
    path('accounts/login/', CustomLoginView.as_view(), name='login'),
    path('accounts/logout/', CustomLogoutView.as_view(), name='logout'),
    path('accounts/register/', RegisterView.as_view(), name='register'),
    path('accounts/', include('new_users.urls')),
]

Courses5_update/Config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('courses/', include('courses.urls', namespace='courses')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Courses5_update/mailing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from courses.views import custom_permission_denied
from mailing.apps import MailingConfig
from mailing.views import MainPage, MailingSrvListView, MailingSrvCreateView, MailingSrvUpdateView, \
    MailingSrvDetailView, MailingSrvDeleteView, MailListView, MailCreateView, MailUpdateView, MailDetailView, \
    MailDeleteView, ClientListView, ClientCreateView, ClientUpdateView, ClientDetailView, ClientDeleteView, \
    LogListView, LogDetailView, LogDeleteView, send_mailing_btn, MailingSrvCustomUpdateView

app_name = MailingConfig.name

urlpatterns = [
    path('', cache_page(60)(MainPage.as_view()), name='home'),
    path('mailings_list/', MailingSrvListView.as_view(), name='mailings_list'),
    path('mailings_create/', MailingSrvCreateView.as_view(), name='mailings_create'),
    path('mailings_update/<int:pk>/', MailingSrvUpdateView.as_view(), name='mailings_update'),
    path('mailings_custom_update/<int:pk>/', MailingSrvCustomUpdateView.as_view(), name='mailings_custom_update'),
    path('mailings_detail/<int:pk>/', MailingSrvDetailView.as_view(), name='mailings_detail'),
    path('mailings_delete/<int:pk>/', MailingSrvDeleteView.as_view(), name='mailings_delete'),
    path('<int:pk>/', send_mailing_btn, name='send_mailing_btn'),
    path('mail_list/', MailListView.as_view(), name='mail_list'),
    path('mail_create/', MailCreateView.as_view(), name='mail_create'),
    path('mail_update/<int:pk>/', MailUpdateView.as_view(), name='mail_update'),
    path('mail_detail/<int:pk>/', MailDetailView.as_view(), name='mail_detail'),
    path('mail_delete/<int:pk>/', MailDeleteView.as_view(), name='mail_delete'),
    path('client_list/', ClientListView.as_view(), name='client_list'),
    path('client_create/', ClientCreateView.as_view(), name='client_create'),
    path('client_update/<int:pk>/', ClientUpdateView.as_view(), name='client_update'),
    path('client_detail/<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
    path('client_delete/<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),
    path('log_list/', LogListView.as_view(), name='log_list'),
    path('log_detail/<int:pk>/', LogDetailView.as_view(), name='log_detail'),
    path('log_delete/<int:pk>/', LogDeleteView.as_view(), name='log_delete'),
    path('access_denied/', custom_permission_denied, name='access_denied'),
]

Courses5_update/courses/models.py
from django.db import models

# Create your models here.

NULLABLE = {
    'null': True,
    'blank': True,
}


class Blogpost(models.Model):
    """
    Модель для хранения информации о публикациях в блоге.
    """
    title = models.CharField(max_length=150, verbose_name='заголовок')
    content = models.TextField(verbose_name='содержимое', **NULLABLE)
    preview = models.ImageField(upload_to='courses/', verbose_name='изображение', **NULLABLE)
    views_count = models.IntegerField(default=0, verbose_name='просмотры')
    date_create = models.DateTimeField(auto_now_add=True, verbose_name='дата публикации')
    is_published = models.BooleanField(default=True,verbose_name='опубликовано')

    def __str__(self):
        return f'Публикация: {self.title}'

    class Meta:
        verbose_name = 'публикация'
        verbose_name_plural = "публикации"
        ordering = ("-date_create",)

Courses5_update/mailing/models.py
"""
Модуль содержит описание классов для работы с клиентами, письмами, рассылками и отчетами.
"""

from django.db import models
from django.utils import timezone

from users.models import User


NULLABLE = {
    'null': True,
    'blank': True,
}


class Client(models.Model):
    """
    Модель для хранения информации о клиентах.
    """
    owner = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='пользователь-владелец',
        **NULLABLE)
    email = models.EmailField(
        max_length=100,
        unique=True,
        verbose_name='почтовый адрес')
    initials = models.CharField(
        max_length=50,
        verbose_name='инициалы')
    comment = models.TextField(
        verbose_name='комментарий',
        **NULLABLE)

    def __str__(self):
        return f'{self.initials} ({self.email})'

    class Meta:
        verbose_name = 'клиент'
        verbose_name_plural = 'клиенты'


class Mail(models.Model):
    """
    Модель для хранения информации о письмах.
    """
    owner = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='пользователь',
        **NULLABLE)
    subject = models.CharField(
        max_length=150,
        verbose_name='тема письма')
    content = models.TextField(
        verbose_name='содержание письма')

    mailings = models.ForeignKey(
        'MailingSrv',
        on_delete=models.CASCADE,
        verbose_name='рассылки',
        related_name='mails',
        **NULLABLE)

    def __str__(self):
        return self.subject

    class Meta:
        verbose_name = 'письмо'
        verbose_name_plural = 'письма'


class MailingSrv(models.Model):
    """
    Модель для хранения информации о рассылках.
    """

    AT_ONCE = 'один раз'
    BY_DAY = 'раз в день'
    BY_WEEK = 'раз в неделю'
    BY_MONTH = 'раз в месяц'

    FREQUENCY = [
        (AT_ONCE, 'один раз'),
        (BY_DAY, 'раз в день'),
        (BY_WEEK, 'раз в неделю'),
        (BY_MONTH, 'раз в месяц')
    ]

    CREATED = 'создана'
    PROCESSING = 'запущена'
    FINISHED = 'завершена'

    STATUS = [
        (CREATED, 'создана'),
        (PROCESSING, 'запущена'),
        (FINISHED, 'завершена')
    ]

    owner = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='пользователь',
        **NULLABLE)
    recipients = models.ManyToManyField(
        Client,
        verbose_name='получатели рассылки')
    mail = models.ForeignKey(
        Mail,
        on_delete=models.CASCADE,
        verbose_name='письмо',
        **NULLABLE)
    start = models.DateTimeField(
        default=timezone.now,
        verbose_name='время начала рассылки')
    next = models.DateTimeField(
        default=timezone.now,
        verbose_name='время следующей рассылки')
    finish = models.DateTimeField(
        verbose_name='время завершения рассылки')
    status = models.CharField(
        max_length=100,
        choices=STATUS,
        default=STATUS[0],
        verbose_name='статус рассылки')
    frequency = models.CharField(
        max_length=50,
        choices=FREQUENCY,
        verbose_name='периодичность рассылки')
    is_activated = models.BooleanField(
        default=True,
        verbose_name='метка активности')

    def __str__(self):
        return f'Рассылка_{self.pk}: {self.frequency} - {self.status}'

    class Meta:
        verbose_name = 'параметр рассылки'
        verbose_name_plural = 'параметры рассылок'
        ordering = ('pk',)

        permissions = [
            ('set_is_activated', 'переключатель метки активности')
        ]


class Log(models.Model):
    """
    Модель для хранения отчетов о рассылках.
    """

    attempt_time = models.DateTimeField(
        auto_now=True,
        verbose_name='время последней попытки')
    status = models.CharField(
        max_length=50,
        verbose_name='статус попытки',
        default='попытка не инициирована')
    server_response = models.TextField(
        verbose_name='ответ почтового сервера',
        **NULLABLE)
    mailing = models.ForeignKey(
        MailingSrv,
        on_delete=models.CASCADE,
        verbose_name='рассылка',
        **NULLABLE)

    def __str__(self):
        return f'Отчет {self.pk}:  Статус - {self.status}( Когда - {self.attempt_time})'

    class Meta:
        verbose_name = 'отчет'
        verbose_name_plural = 'отчеты'
        ordering = ('mailing',)

Courses5_update/mailing/forms.py
from django import forms
from django.forms import DateTimeInput

from mailing.models import MailingSrv, Mail, Client


class StyleFormMiXin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name != 'is_activated' and field_name != 'is_published':
                field.widget.attrs['class'] = 'form-control'


class MailingSrvForm(StyleFormMiXin, forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        user = self.request.user
        super().__init__(*args, **kwargs)
        self.fields['recipients'].queryset = Client.objects.filter(owner=user)
        self.fields['mail'].queryset = Mail.objects.filter(owner=user)

    start = forms.DateTimeField(
        label='Время старта рассылки',
        required=False,
        widget=DateTimeInput(attrs={'type': 'datetime-local', 'class': 'form-control'}, format='%Y-%m-%dT%H:%M')
    )

    finish = forms.DateTimeField(
        label='Время окончания рассылки',
        required=False,
        widget=DateTimeInput(attrs={'type': 'datetime-local', 'class': 'form-control'}, format='%Y-%m-%dT%H:%M')
    )

    class Meta:
        model = MailingSrv
        exclude = ('next', 'owner', 'is_activated',)


class MailingSrvCustomForm(StyleFormMiXin, forms.ModelForm):

    class Meta:
        model = MailingSrv
        fields = ('is_activated',)


class MailForm(StyleFormMiXin, forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        user = self.request.user
        super().__init__(*args, **kwargs)
        self.fields['mailings'].queryset = MailingSrv.objects.filter(owner=user)

    class Meta:
        model = Mail
        exclude = ('owner',)


class ClientForm(StyleFormMiXin, forms.ModelForm):
    class Meta:
        model = Client
        exclude = ('owner',)

Courses5_update/mailing/templates/mailing/access_denied.html
{% extends 'mailing/base.html' %}

{% block content %}
<div style="display: flex; justify-content: center;">

    <h4 class="card-title">
        Доступ ограничен. Обратитесь к администратору.
    </h4>

</div>
{% endblock %}

Courses5_update/mailing/templates/mailing/client_detail.html
{% extends 'mailing/base.html' %}

{% block content %}

<div class="container">
    <div class="card-deck mb-3 text-center">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Клиент номер: {{ object.id }}</h4>
            </div>
            <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4">
                    <li>Инициалы клиента: {{ object.initials | upper }}</li>
                    <li>Почтовый адрес клиента: {{ object.email }}</li>
                    <li>Комментарий: {{ object.comment }}</li>
                </ul>
                <div class="btn-group">
                    <a href="{% url 'mailing:client_delete' object.pk %}" type="button"
                        class="btn btn-sm btn-outline-success">Удалить</a>
                    <a href="{% url 'mailing:client_update' object.pk %}" type="button"
                        class="btn btn-sm btn-outline-success">Редактировать</a>
                    <a href="{% url 'mailing:client_list' %}" type="button" class="btn btn-sm btn-outline-success">К
                        списку</a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

Courses5_update/mailing/templates/mailing/client_form.html
{% extends 'mailing/base.html' %}

{% block content %}
<section class="jumbotron text-center">
    <div class="container">
        <div class="col-12">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <form method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <button type="submit" class="btn btn-success">
                                    {% if object %}
                                    Сохранить изменения
                                    {% else %}
                                    Создать
                                    {% endif %}
                                </button>
                                <a href="{% url 'mailing:client_list' %}" class="btn btn-success">Отмена</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

Courses5_update/mailing/templates/mailing/client_list.html
{% extends 'mailing/base.html' %}

{% block content %}

<div class="container">
    <a href="{% url 'mailing:client_create' %}" class="btn btn-success">Добавить клиента</a>
</div>

<div class="container">
    {% for object in object_list %}
    <div class="card-deck mb-3 text-center">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Клиент номер: {{ object.id }}</h4>
            </div>
            <div class="card-body">
                <details>
                    <summary>Подробности</summary>
                    <ul class="list-unstyled mt-3 mb-4">
                        <li>Инициалы клиента: {{ object.initials | upper }}</li>
                        <li>Почтовый адрес клиента: {{ object.email }}</li>
                        <li>Комментарий: {{ object.comment }}</li>
                    </ul>
                </details>

                <div class="btn-group">
                    <a href="{% url 'mailing:client_detail' object.pk %}" type="button"
                        class="btn btn-sm btn-outline-success">Посмотреть</a>
                    <a href="{% url 'mailing:client_update' object.pk %}" type="button"
                        class="btn btn-sm btn-outline-success">Редактировать</a>
                    <a href="{% url 'mailing:client_delete' object.pk %}" type="button"
                        class="btn btn-sm btn-outline-success">Удалить</a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

Courses5_update/mailing/templates/mailing/home.html
{% extends 'mailing/base.html' %}

{% block content %}

<div class="container">
    <div class="card-deck mb-3 text-center">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Рассылки</h4>
            </div>
            <div class="card-body">
                <div class="d-flex justify-content-end mt-auto">
                    <ol class="list-group list-group">
                        <li class="list-group-item d-flex justify-content-between align-items-start">
                            <div class="ms-2 me-auto">
                                <small class="text-body-secondary">Количество рассылок всего:</small>
                                <span class="badge bg-success rounded-pill">{{ mailings_count }}</span>
                                <hr class="my-1 "> <!-- Горизонтальный разделитель -->
                                <small class="text-body-secondary">Количество со статусом "активна":</small>
                                <span class="badge bg-success rounded-pill">{{ active_mailings_count }}</span>
                            </div>
                        </li>
                    </ol>
                </div>
            </div>
            <div class="card-footer">
                {% if user.is_superuser or not user.groups.exists %}
                {% if user.is_authenticated %}
                <a href="{% url 'mailing:mailings_create' %}" class="btn btn-lg btn-block btn-outline-success">Добавить
                    рассылку</a>
                {% endif %}
                {% endif %}
            </div>
        </div>
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Клиенты</h4>
            </div>
            <div class="card-body">
                <div class="d-flex justify-content-end mt-auto">
                    <ol class="list-group list-group">
                        <li class="list-group-item d-flex justify-content-between align-items-start">
                            <div class="ms-2 me-auto">
                                <small class="text-body-secondary">Количество уникальных клиентов:</small>
                                <span class="badge bg-success rounded-pill">{{ unique_clients_count }}</span>
                            </div>
                        </li>
                    </ol>
                </div>
            </div>
            <div class="card-footer">
                {% if user.is_superuser or not user.groups.exists %}
                {% if user.is_authenticated %}
                <a href="{% url 'mailing:client_create' %}" class="btn btn-lg btn-block btn-outline-success">Добавить
                    клиента</a>
                {% endif %}
                {% endif %}
            </div>
        </div>
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Пользователи</h4>
            </div>
            <div class="card-body">
                <div class="d-flex justify-content-end mt-auto">
                    <ol class="list-group list-group">
                        <li class="list-group-item d-flex justify-content-between align-items-start">
                            <div class="ms-2 me-auto">
                                <small class="text-body-secondary">Количество пользователей:</small>
                                <span class="badge bg-success rounded-pill">{{ unique_users_count }}</span>
                                <hr class="my-1 "> <!-- Горизонтальный разделитель -->
                            </div>
                        </li>
                    </ol>
                </div>
            </div>
            <div class="card-footer">
                {% if user.is_superuser or not user.groups.exists %}
                {% if user.is_authenticated %}
                <a class="btn btn-lg btn-block btn-outline-success"
                    href="{% url 'users:register' %}">Зарегистрироваться</a>
                {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
    {% if blogpost_list %}
    <hr class="my-4"> <!-- Горизонтальный разделитель -->
    <h4 class="text-center">Публикации нашего блога:</h4>
    <hr class="my-4"> <!-- Горизонтальный разделитель -->
    <div class="card-deck mb-3 text-center">
        {% for post in blogpost_list %}
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{ post.title | truncatechars:33 }}</h4>
            </div>
            <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4">
                    <li>{{ post.content | truncatechars:111 }}</li>
                </ul>
            </div>
            <div class="card-footer">
                <div class="d-flex justify-content-end mt-auto">
                    <ol class="list-group list-group">
                        <li class="list-group-item d-flex justify-content-between align-items-start">
                            <div class="ms-2 me-auto">
                                <small class="text-body-secondary">Просмотры:</small>
                                <span class="badge bg-success rounded-pill">{{ post.views_count }}</span>
                            </div>
                        </li>
                    </ol>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endif %}
</div>

{% endblock %}

Courses5_update/mailing/templates/mailing/log_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
<section class="jumbotron text-center">
    <div class="container">
        <div class="col-12">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <form method="post">
                                {% csrf_token %}
                                <p>Вы действительно хотите удалить отчет "{{ object.pk }}" ?</p>
                                <button type="submit" class="btn btn-danger">Подтвердить</button>
                                <a href="{% url 'mailing:log_detail' object.pk %}" class="btn btn-success">Отмена</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

Courses5_update/mailing/templates/mailing/log_detail.html
{% extends 'mailing/base.html' %}

{% block content %}


<div class="container">
    {% for data in mailing_data %}
    <div class="card-deck mb-3 text-center">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h6 class="my-0 font-weight-normal">{{ data.log.mailing }}</h6>
                <h6 class="my-0 font-weight-normal">Время начала: {{ data.log.mailing.start|date:"Y-m-d H:i" }}</h6>
            </div>
            <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4">
                    <li>Время последней попытки: {{ data.log.attempt_time }}</li>
                    <li>Статус попытки рассылки: {{ data.log.status }}</li>
                    <li>Ответ почтового сервера: {{ data.log.server_response }}</li>
                </ul>

                <hr>

                <ul class="list-unstyled mt-3 mb-4">
                    {% for recipient_data in data.recipients_data %}
                    <li>Почтовый ящик: {{ recipient_data.email }} (ФИО: {{ recipient_data.initials }})</li>
                    {% endfor %}
                </ul>

                <div class="btn-group">
                    <a href="{% url 'mailing:log_list' %}" type="button" class="btn btn-sm btn-outline-success">К
                        списку</a>
                    <a href="{% url 'mailing:log_delete' data.log.pk %}" type="button"
                        class="btn btn-sm btn-outline-success">Удалить</a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

Courses5_update/mailing/templates/mailing/log_list.html
{% extends 'mailing/base.html' %}

{% block content %}

<div class="container">
    <a href="{% url 'mailing:mailings_create' %}" class="btn btn-success">Добавить рассылку</a>
</div>

<div class="container">
    {% for data in mailing_data %}
    <div class="card-deck mb-3 text-center">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h6 class="my-0 font-weight-normal">{{ data.log.mailing }}</h6>
                <h6 class="my-0 font-weight-normal">Время начала: {{ data.log.mailing.start|date:"Y-m-d H:i" }}</h6>
            </div>
            <div class="card-body">
                <details>
                    <summary>Подробности</summary>
                    <ul class="list-unstyled mt-3 mb-4">
                        <li>Время последней попытки: {{ data.log.attempt_time }}</li>
                        <li>Статус попытки рассылки: {{ data.log.status }}</li>
                        <li>Ответ почтового сервера: {{ data.log.server_response }}</li>
                    </ul>

                    <hr>

                    <ul class="list-unstyled mt-3 mb-4">
                        {% for recipient_data in data.recipients_data %}
                        <li>Почтовый ящик: {{ recipient_data.email }} (ФИО: {{ recipient_data.initials }})</li>
                        {% endfor %}
                    </ul>
                </details>

                <div class="btn-group">
                    <a href="{% url 'mailing:log_detail' data.log.pk %}" type="button"
                        class="btn btn-sm btn-outline-success">Посмотреть</a>
                    <a href="{% url 'mailing:log_delete' data.log.pk %}" type="button"
                        class="btn btn-sm btn-outline-success">Удалить</a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

Courses5_update/mailing/templates/mailing/mail_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
<section class="jumbotron text-center">
    <div class="container">
        <div class="col-12">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <form method="post">
                                {% csrf_token %}
                                <p>Вы действительно хотите удалить письмо "{{ object.pk }}" ?</p>
                                <button type="submit" class="btn btn-danger">Подтвердить</button>
                                <a href="{% url 'mailing:mail_detail' object.pk %}" class="btn btn-success">Отмена</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

Courses5_update/mailing/templates/mailing/mailingsrv_detail.html
{% extends 'mailing/base.html' %}

{% block content %}

<div class="container">
    <div class="card-deck mb-3 text-center">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Рассылка номер: {{ object.id }}</h4>
            </div>
            <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4">
                    <li>Периодичность рассылки: {{ object.frequency }}</li>
                    <li>Время начала рассылки: {{ object.start }}</li>
                    <li>Время следующей рассылки: {{ object.next }}</li>
                    <li>Время завершения рассылки: {{ object.finish }}</li>
                    <li>Статус рассылки: {{ object.status }}</li>
                </ul>

                <hr>

                <ul class="list-unstyled mt-3 mb-4">
                    {% for recipient_data in mailing_data.0.recipients_data %}
                    {% if mail_subject %}
                    <li>Тема письма: {{ mail_subject }}</li>
                    {% else %}
                    <li>Письмо не назначено</li>
                    {% endif %}
                    <li>Почтовый ящик: {{ recipient_data.email }} (ФИО: {{ recipient_data.initials }})</li>
                    {% endfor %}
                </ul>


                <div class="btn-group">

                    {% if perms.mailing.set_is_activated %}
                    <a href="{% url 'mailing:mailings_custom_update' object.pk %}" type="button"
                        class="btn btn-sm btn-outline-success">Редактировать</a>

                    <a href="{% url 'mailing:mailings_list' %}" type="button" class="btn btn-sm btn-outline-success">К
                        списку</a>
                    {% else %}
                    <a href="{% url 'mailing:mailings_delete' object.pk %}" type="button"
                        class="btn btn-sm btn-outline-success">Удалить</a>
                    <a href="{% url 'mailing:mailings_update' object.pk %}" type="button"
                        class="btn btn-sm btn-outline-success">Редактировать</a>
                    <a href="{% url 'mailing:mailings_list' %}" type="button" class="btn btn-sm btn-outline-success">К
                        списку</a>

                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

Courses5_update/mailing/templates/mailing/mailingsrv_list.html
{% extends 'mailing/base.html' %}

{% block content %}

<div class="container">
    {% if user.is_superuser or not user.groups.exists %}
    <a href="{% url 'mailing:mailings_create' %}" class="btn btn-success">Добавить рассылку</a>
    {% endif %}
</div>

<div class="container">
    {% for object in object_list %}
    {% if user == object.owner or perms.mailing.view_mailingsrv %}
    <div class="card-deck mb-3 text-center">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <div class="d-flex justify-content-end mt-auto">
                    <ol class="list-group list-group">
                        <li class="list-group-item d-flex justify-content-between align-items-start">
                            <div class="ms-2 me-auto">
                                {% if object.is_activated %}
                                <small class="text-body-secondary activated" style="color: green;">активна</small>
                                {% else %}
                                <small class="text-body-secondary" style="color: red;">заблокирована</small>
                                {% endif %}
                            </div>
                        </li>
                    </ol>
                </div>
                <h4 class="my-0 font-weight-normal">Рассылка номер: {{ object.id }}</h4>
            </div>
            <div class="card-body">
                <details>
                    <summary>Посмотреть</summary>
                    <ul class="list-unstyled mt-3 mb-4">
                        <li>Периодичность рассылки: {{ object.frequency }}</li>
                        <li>Время начала рассылки: {{ object.start }}</li>
                        <li>Время завершения рассылки: {{ object.finish }}</li>
                        <li>Статус рассылки: {{ object.status }}</li>
                    </ul>
                </details>

                <div class="btn-group">
                    <a href="{% url 'mailing:mailings_detail' object.pk %}" type="button"
                        class="btn btn-sm btn-outline-success">Подробности</a>
                    {% if user.is_superuser or not user.groups.exists %}
                    {% if object.is_activated %}
                    <form action="{% url 'mailing:send_mailing_btn' object.pk %}" method="post">
                        {%csrf_token%}
                        <button class="btn btn-success" type="submit">Выполнить</button>
                    </form>
                    {% endif %}
                    {% endif %}

                </div>
            </div>
        </div>
    </div>
    {% endif %}
    {% endfor %}
</div>

{% endblock %}